site_name: 蒋乐兴的玫瑰园
theme:
  name: material
  palette:
    primary: black
  font:
    text: 仿宋 Noto Sans SC
  language: zh
  favicon: docs/favicon.ico
# extra:
#   generator: false
copyright: 粤ICP备18030181号